[theme]
background = "2e3440"
title = "f7768e"
hightlight = "33467c" 
hightlight_inactive = "7aa2f7"
hightlight_text = "c0caf5"
text = "c0caf5"
search_match = "f7768e"

[keybindings]
down.key = "j"
up.key = "k"
left.key = "h"
right.key = "l"

[features]
toc = true
links = false
