[theme]
background = "black"
title = "f7768e"
hightlight = "33467c" 
hightlight_inactive = "7aa2f7"
hightlight_text = "c0caf5"
text = "c0caf5"
search_match = "f7768e"

[theme.search_bar]
background = "black"

[parser]
toc = false
